---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/"
)
set.seed(0)
```

# mlesky : Maximum likelihood phylodynamic inference

This package performs inference of past population size dynamics from a dated phylogeny using a maximum likelihood approach. 
The main features are as follows:

* Three different phylodynamic models are implemented (skygrid, skygrowth and skykappa)
* A novel cross-validation approach is used for selecting the smoothing parameter 
* The resolution of the grid can be selected using AIC or BIC
* Covariate data can be included into the analysis to quantify association
* Multiple phylogenies can be analysed simultaneously that share the same demographic function

For a complete description of the statistical methodology underpinning this package, see our paper:

Model design for nonparametric phylodynamic inference and applications to pathogen surveillance  
Xavier Didelot, Vinicius Franceschi, Simon D. W Frost, Ann Dennis, Erik M Volz  
Virus Evolution, Volume 9, Issue 1, 2023, vead028, https://doi.org/10.1093/ve/vead028

## Installation

In R, install the `devtools` package and run 
```
devtools::install_github('emvolz-phylodynamics/mlesky')
```

## Documentation

See the vignettes in the R package for examples of how to use mlesky.





